# Generated by Django 5.0.4 on 2025-12-19 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='price_per_night',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='property',
            name='ai_verified_score',
            field=models.TextField(default='No evaluation yet'),
        ),
    ]
