# Generated by Django 5.0.4 on 2025-12-21 13:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('api', '0002_property_price_per_night_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavouriteProperty',
            fields=[
                ('favourite_id', models.AutoField(primary_key=True, serialize=False)),
                ('added_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourite_properties', to='accounts.guestprofile')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='added_by_guests', to='api.property')),
            ],
            options={
                'unique_together': {('guest', 'property')},
            },
        ),
    ]
